version: 2
updates:
  - package-ecosystem: "pip"
    insecure-external-code-execution: "deny"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
