name: main branch - test; deploy (ecr)

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  test:
    uses: ./.github/workflows/_test.yml

  deploy:
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit
    needs: [test]
    with:
      target: ghcr
