name: Manual deploy

on:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/_test.yml

  deploy:
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit
    needs: [test]
    with:
      target: ghcr
